### ISSUE TITLE
Unhandled execption in script

### ISSUE THREAD

**Issue by ASKUTKRIMSON** [m-jishnu/alt-app-installer#31]
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "maingui.py", line 22, in <module>
System.IO.FileNotFoundException: Unable to find assembly 'C:\WINDOWS\system32\data\System.Management.Automation.dll'.

   в Python.Runtime.CLRModule.AddReference(String name)
![Безымянный](https://github.com/m-jishnu/alt-app-installer/assets/84001806/db3eb0d2-5cce-44c5-87cd-7fff8a8990d1)

**Comment by m-jishnu** [comment]
try this and tell me what it shows in the terminal console 
https://we.tl/t-4gxmeCiWqq
