### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by mrrezaie** [m-jishnu/alt-app-installer#40]
Hi, thanks for this app. 

Any idea the why it can not download any apps?
```
[python logs] 
[05-08-2023 14:47:05]

Traceback (most recent call last):
  File "utls.py", line 117, in run
  File "core.py", line 264, in <lambda>
  File "core.py", line 252, in download_install_thread
Exception: Download Error Occured!
```
I noticed that the size of the files in the alt app installer\downloads directory changed during the download process, but it did not complete successfully. Is there a way to fix it?

**Comment by m-jishnu** [comment]
try clear cache [option --> clear cache ] and try again

**Comment by mrrezaie** [comment]
Thanks for your response, but no avail. The same error raised.

**Comment by m-jishnu** [comment]
Then i need some more info
1) your system architecture
2) windows version ( like win 11 22h2 (22h2 part needed))
3) the app you were trying to install
4) the full log.txt file (found in alt app installer folder or help --> logs)

**Comment by mrrezaie** [comment]
Sure,
1. x64
2. Windows 10, 22H2
3. Telegram Desktop
4. 

> [python logs] 
[05-08-2023 14:47:05]
Traceback (most recent call last):
  File "utls.py", line 117, in run
  File "core.py", line 264, in <lambda>
  File "core.py", line 252, in download_install_thread
Exception: Download Error Occured!

However, I succesfully installed SoundCloud app. I think that's because it has a small size. Maybe the internet connection is the reason.

**Comment by m-jishnu** [comment]
i tried downloading telegram and it downloaded and installed successfully, since you were able to download soundcloud app it is likely that the cause of issue is slow internet speed. but for accurate result can you try the debugging version and tell me what it says in the console (terminal) when the error occurs.
link:  https://www.mediafire.com/file/hnki5j6ezx0h9jp/alt_app_installer.exe/file

<img width="1023" alt="Screenshot 2023-07-27 234425" src="https://github.com/m-jishnu/alt-app-installer/assets/83004520/4ac08f3b-84f8-464f-bf18-6d78db641c6e">

**Comment by mrrezaie** [comment]
The debugging version downloaded and installed the Telegram app successfully. But I re-tested the original version and it failed again.

**Comment by m-jishnu** [comment]
oh that's weird, the debug version and latest version have the same underlying code the debug version just has a console that's all so there should not be any difference between the two, try re-downloading latest version from GitHub and try

**Comment by mrrezaie** [comment]
Hi, I retested both versions and sometimes failed but finally, I could download and install the app with both versions. This error also appeared in the console:

```
js: StatusCode: ECONNABORTED GetApplicationsList
Traceback (most recent call last):
  File "urllib3\connection.py", line 200, in _new_conn
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1092, in _validate_conn
  File "urllib3\connection.py", line 604, in connect
  File "urllib3\connection.py", line 209, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x00000264D38CC190>, 'Connection to storeedgefd.dsx.mp.microsoft.com timed out. (connect timeout=20)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storeedgefd.dsx.mp.microsoft.com', port=443): Max retries exceeded with url: /v9.0/products/9NZTWSQNTD0S?market=US&locale=en-us&deviceFamily=Windows.Desktop (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000264D38CC190>, 'Connection to storeedgefd.dsx.mp.microsoft.com timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "utls.py", line 117, in run
  File "core.py", line 204, in <lambda>
  File "modules\url_gen.py", line 58, in url_generator
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 507, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='storeedgefd.dsx.mp.microsoft.com', port=443): Max retries exceeded with url: /v9.0/products/9NZTWSQNTD0S?market=US&locale=en-us&deviceFamily=Windows.Desktop (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000264D38CC190>, 'Connection to storeedgefd.dsx.mp.microsoft.com timed out. (connect timeout=20)'))
```
Could you increase the default timeout?

**Comment by m-jishnu** [comment]
can you tell me if it is working or not

**Comment by mrrezaie** [comment]
Sometimes it worked but mostly I got this:
```
Error in thread 18: (ConnectionError, ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
Retry function Error: (SSLError, HTTPSConnectionPool(host='storeedgefd.dsx.mp.microsoft.com', port=443): Max retries exceeded with url: /v9.0/products/9NZTWSQNTD0S?market=US&locale=en-us&deviceFamily=Windows.Desktop (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1002)'))))
retrying...
Error in thread 2: (ConnectionError, HTTPConnectionPool(host='tlu.dl.delivery.mp.microsoft.com', port=80): Read timed out.)
retrying...
corrupted file!
corrupted file!
corrupted file!
corrupted file!
corrupted file!
corrupted file!
corrupted file!
corrupted file!
corrupted file!
corrupted file!
corrupted file!
corrupted file!
corrupted file!
corrupted file!
corrupted file!
corrupted file!
retrying...
Error in thread 9: (ConnectionError, HTTPConnectionPool(host='tlu.dl.delivery.mp.microsoft.com', port=80): Read timed out.)
Error in thread 4: (ConnectionError, ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
retrying...
corrupted file!
corrupted file!
corrupted file!
retrying...
Error in thread 8: (ConnectionError, HTTPConnectionPool(host='tlu.dl.delivery.mp.microsoft.com', port=80): Read timed out.)
Download Failed!
Traceback (most recent call last):
  File "utls.py", line 117, in run
  File "core.py", line 264, in <lambda>
  File "core.py", line 252, in download_install_thread
Exception: Download Error Occured!
Error in thread 1: (ConnectionError, HTTPConnectionPool(host='tlu.dl.delivery.mp.microsoft.com', port=80): Read timed out.)
Error in thread 9: (ConnectionError, ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
Error in thread 1: (ConnectionError, HTTPConnectionPool(host='tlu.dl.delivery.mp.microsoft.com', port=80): Read timed out.)
Error in thread 15: (ConnectionError, HTTPConnectionPool(host='tlu.dl.delivery.mp.microsoft.com', port=80): Read timed out.)
Error in thread 18: (ReadTimeout, HTTPConnectionPool(host='tlu.dl.delivery.mp.microsoft.com', port=80): Read timed out. (read timeout=60))
```
That's fine, my connection is the issue. I appreciate your help.
